name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
    name:
        required: true
        description: "The add-on name (name of the .toc file)"
    path:
        required: true
        description: "Path to the directory with all the files. The toc file must be at the root of this directory."
    tag:
        required: true
        description: "The tag, like refs/tag/XXX"
    cf-api-key:
        required: false
        description: "The Curseforge API Key"
    cf-id:
        required: false
        description: "The Curseforge project Id (a number)"
    wowi-api-token:
        required: false
        description: "The WoWInterface API Token"
    wowi-id:
        required: false
        description: "The WoWInterface project Id (a number)"
    changelog:
        required: false
        description: "The changelog in Markdown format"
outputs:
    zip-path:
        description: "Path to the created ZIP file"
    zip-name:
        description: "Name of the created ZIP file"
    changelog:
        description: "The Changelog for this release only"
runs:
    using: "node12"
    main: "dist/index.js"
